"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 4.2.30.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import os
from pathlib import Path
from dotenv import load_dotenv

# Load environment variables from .env file
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-t^jhd0u4!dkm&pm*=c1))^m9z2168*se9x=wt%2)5ghiapwpgw'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['localhost', '127.0.0.1']
render_external_hostname = os.getenv('RENDER_EXTERNAL_HOSTNAME')
if render_external_hostname:
    ALLOWED_HOSTS.append(render_external_hostname)


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    'app',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

from urllib.parse import urlparse

database_url = os.getenv('DATABASE_URL')
db_host = os.getenv('DB_HOST')
db_password = os.getenv('DB_PASSWORD')

if database_url:
    try:
        parsed = urlparse(database_url)
        # Parse connection details from the URL
        DATABASES = {
            'default': {
                'ENGINE': 'django.db.backends.postgresql',
                'NAME': parsed.path.lstrip('/') or 'postgres',
                'USER': parsed.username or 'postgres',
                'PASSWORD': parsed.password or '',
                'HOST': parsed.hostname or 'localhost',
                'PORT': str(parsed.port) if parsed.port else '5432',
            }
        }
        print("Database: Connected to Supabase (PostgreSQL) via DATABASE_URL")
    except Exception as url_err:
        print(f"Database: Failed to parse DATABASE_URL ({url_err}). Falling back to local SQLite.")
        DATABASES = {
            'default': {
                'ENGINE': 'django.db.backends.sqlite3',
                'NAME': BASE_DIR / 'db.sqlite3',
            }
        }
elif db_host and db_password:
    # Fallback to separate variables
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.getenv('DB_NAME', 'postgres'),
            'USER': os.getenv('DB_USER', 'postgres'),
            'PASSWORD': db_password,
            'HOST': db_host,
            'PORT': os.getenv('DB_PORT', '5432'),
        }
    }
    print("Database: Connected to Supabase (PostgreSQL) via individual host settings")
else:
    # Fallback to local SQLite
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }
    print("Database: Connected to Local SQLite")



# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Storage settings for static files compression
STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}

# Media files (user uploads)
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
MEDIA_URL = '/media/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# ── CORS Configuration ─────────────────────────────────────────────────────
CORS_ALLOW_CREDENTIALS = True
CORS_ALLOWED_ORIGINS = [
    'http://localhost:3000',
    'http://127.0.0.1:3000',
]
frontend_url_env = os.getenv('FRONTEND_URL')
if frontend_url_env:
    CORS_ALLOWED_ORIGINS.append(frontend_url_env)

CSRF_TRUSTED_ORIGINS = [
    'http://localhost:3000',
    'http://127.0.0.1:3000',
]
if frontend_url_env:
    CSRF_TRUSTED_ORIGINS.append(frontend_url_env)


# ── File Upload Limits ──────────────────────────────────────────────────────
DATA_UPLOAD_MAX_MEMORY_SIZE = 10 * 1024 * 1024   # 10 MB
FILE_UPLOAD_MAX_MEMORY_SIZE = 10 * 1024 * 1024   # 10 MB

# ── Google Drive Configuration ──────────────────────────────────────────────
GOOGLE_DRIVE_FOLDER_ID = os.getenv('GOOGLE_DRIVE_FOLDER_ID', '126PYWn4ggyOHaFvdpd8T9iri35VAZ2Ix')

import json

# Programmatically build OAuth Client Secret JSON
oauth_client_id = os.getenv('GOOGLE_OAUTH_CLIENT_ID')
oauth_project_id = os.getenv('GOOGLE_OAUTH_PROJECT_ID')
oauth_client_secret = os.getenv('GOOGLE_OAUTH_CLIENT_SECRET')
oauth_redirect_uri = os.getenv('GOOGLE_OAUTH_REDIRECT_URI', 'http://localhost:8000/api/auth/gdrive/callback')

if oauth_client_id and oauth_client_secret:
    GOOGLE_OAUTH_CLIENT_SECRET_JSON = json.dumps({
        "web": {
            "client_id": oauth_client_id,
            "project_id": oauth_project_id,
            "auth_uri": "https://accounts.google.com/o/oauth2/auth",
            "token_uri": "https://oauth2.googleapis.com/token",
            "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
            "client_secret": oauth_client_secret,
            "redirect_uris": [oauth_redirect_uri]
        }
    })
else:
    GOOGLE_OAUTH_CLIENT_SECRET_JSON = None

# Programmatically build Service Account Credentials JSON
sa_project_id = os.getenv('GOOGLE_SERVICE_ACCOUNT_PROJECT_ID')
sa_private_key_id = os.getenv('GOOGLE_SERVICE_ACCOUNT_PRIVATE_KEY_ID')
sa_private_key = os.getenv('GOOGLE_SERVICE_ACCOUNT_PRIVATE_KEY')
sa_client_email = os.getenv('GOOGLE_SERVICE_ACCOUNT_CLIENT_EMAIL')
sa_client_id = os.getenv('GOOGLE_SERVICE_ACCOUNT_CLIENT_ID')

if sa_client_email and sa_private_key:
    # Handle private key formatting (newlines)
    clean_key = sa_private_key.replace('\\n', '\n')
    GOOGLE_DRIVE_CREDENTIALS_JSON = json.dumps({
        "type": "service_account",
        "project_id": sa_project_id,
        "private_key_id": sa_private_key_id,
        "private_key": clean_key,
        "client_email": sa_client_email,
        "client_id": sa_client_id,
        "auth_uri": "https://accounts.google.com/o/oauth2/auth",
        "token_uri": "https://oauth2.googleapis.com/token",
        "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
        "client_x509_cert_url": f"https://www.googleapis.com/robot/v1/metadata/x509/{sa_client_email.replace('@', '%40')}",
        "universe_domain": "googleapis.com"
    })
else:
    GOOGLE_DRIVE_CREDENTIALS_JSON = None

GOOGLE_OAUTH_REDIRECT_URI = oauth_redirect_uri
FRONTEND_URL = os.getenv('FRONTEND_URL', 'http://localhost:3000')

