# Generated by Django 4.2.30 on 2026-06-21 07:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0002_apitoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrapperjob',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scrapper_jobs', to=settings.AUTH_USER_MODEL),
        ),
    ]
