# Generated by Django 4.2.30 on 2026-06-21 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_scrapperjob_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrapperjob',
            name='google_drive_file_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
