# Generated by Django 4.2.30 on 2026-06-21 12:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0004_scrapperjob_google_drive_file_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserGoogleDriveConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_json', models.TextField(blank=True, default='', help_text='Full OAuth 2.0 token JSON (access_token, refresh_token, expiry, etc.)')),
                ('folder_id', models.CharField(blank=True, default='', help_text="Google Drive folder ID where this user's files are uploaded.", max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gdrive_config', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Google Drive Config',
                'verbose_name_plural': 'User Google Drive Configs',
            },
        ),
    ]
